// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.SavingsBonds
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("iBonds")]
        public IBonds IBonds { get; set; }

        [JsonProperty("eeBonds")]
        public EeBonds EeBonds { get; set; }

        [JsonProperty("recommendation")]
        public string Recommendation { get; set; }

        [JsonProperty("recommendationReason")]
        public string RecommendationReason { get; set; }

        [JsonProperty("nextRateChange")]
        public DateTimeOffset NextRateChange { get; set; }

        [JsonProperty("lastUpdated")]
        public DateTimeOffset LastUpdated { get; set; }
    }

    public partial class EeBonds
    {
        [JsonProperty("currentRate")]
        public double CurrentRate { get; set; }

        [JsonProperty("guaranteedDoubling")]
        public string GuaranteedDoubling { get; set; }

        [JsonProperty("purchaseLimit")]
        public long PurchaseLimit { get; set; }
    }

    public partial class IBonds
    {
        [JsonProperty("currentRate")]
        public double CurrentRate { get; set; }

        [JsonProperty("fixedRate")]
        public double FixedRate { get; set; }

        [JsonProperty("inflationRate")]
        public double InflationRate { get; set; }

        [JsonProperty("purchaseLimit")]
        public long PurchaseLimit { get; set; }
    }
}
